apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  name: taxicab
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - name: "https"
      port: 443
      targetPort: 8080
      protocol: "TCP"
  selector:
    app: taxicab
